---
title: "第4章 関数"
author: '@nozma'
date: "2018/5/14"
output:
  revealjs::revealjs_presentation:
    pandoc_args: [
      '--from', 'markdown+autolink_bare_uris+tex_math_single_backslash-implicit_figures'
    ]
    theme: black
    transition: fade
    center: false
    progress: true
    css: "for_reveal.css"
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(
  engine.path = list(python = "~/myenv/bin/python3"),
  collapse = TRUE,
  comment = " #>"
  )
```

## 関数とは何か

- **入力値**を受け取り**命令**を実行し、**出力値**を返すまでの複合文

## 関数の呼び出し

- 関数への入力: **引数**
- 引数は関数名に続いて`()`を付け、その内側に書く。
- 雰囲気は数学で出てきた関数の書き方に似ている。
    - 数学の関数: $f(x) = x \times 2$
    - Pythonの関数呼び出し: `print("hoge")`


## 関数を定義する

- 関数は`def`キーワードを使って定義する。

```python
def [関数名]([引数]):
    [関数定義]
```

## $f(x) = x \times 2$を定義する

- 戻り値は`return`に続いて記述する。

```{python}
def f(x):
    return x * 2
```

- 実行例:

```{python}
print(f(10))
```

## 引数の数

- 引数の数は必ずしも1つではなく、0個(引数がない)の場合や2個以上の場合もある。

```{python}
# 引数なしの関数例
def f():
    return 1 + 1

print(f())
```

```{python}
# 引数が3つの関数例
def f(x, y, z):
    return x + y + z

print(f(1, 2, 3))
```


## 組み込み関数

- Pythonに限らず、プログラミング言語には多かれ少なかれ予め用意された関数群が存在する。
- `print()`は組み込み関数の例。

```{python}
# 与えられた文字列を出力する
print("hoge")

# 文字列の長さなど、オブジェクトの長さを返す
len("Monty")

# 与えられたオブジェクトをstr型に変換する
str(100)

# 与えられたオブジェクトをint型に変換する
int("1")

# 与えられたオブジェクトをfloat型に変換する
float(100)
```

## 関数と例外

- 関数によっては、扱えないタイプの入力を受け取ると例外を返すものがある。
- `int()`は整数または浮動小数点数として解釈できない引数を与えると例外を返す。

```python
int("Prince")
#> ValueError: invalid literal for int() with base 10: 'Prince'
```

## 外部からの入力を受け付ける関数

- `input()`は標準入力からの入力を受け取る。
    - シェルで実行した場合はユーザーからの入力を待機する。

```python
age = int(input("年齢を入力してください:"))
if age < 21:
    print("若いですね!")
else:
    print("年取ってますね!")
#> 年齢を入力してください:
#> 32
#> 年取ってますね!
```

## 関数を再利用する

- 関数は**機能をまとめる**ために使える。
- 繰り返し使用すると考えられる操作があれば、それを関数にしておくとコードを短くできる。

```{python}
def even_odd(x):
    if x % 2 == 0:
        print("偶数")
    else:
        print("奇数")
```

```{python}
even_odd(2)
even_odd(3)
```

## オプション引数

- **必須引数**: 関数実行のために必ず入力する必要がある。
- **オプション引数**: 省略できる。省略するとデフォルト値が使用される。
    - オプション引数は`f(x=2)`のようにデフォルト値を設定する。

```{python}
def f(x=2):
    return x ** x
```

```{python}
print(f())
print(f(4))
```

## 変数のスコープ

- 変数を定義すると、同時に**スコープ**が定まる。
- **スコープ**は変数が有効な範囲と言える。
- 関数やクラス(第2部まで待て)の外は**グローバルスコープ**と呼び、ここで定義した変数はどこからでも読み書きできる**グローバル変数**となる。
- 関数やクラス内は**ローカルスコープ**と呼び、ローカルスコープ内で定義された変数はローカルスコープ内でしか読み書きできない**ローカル変数**となる。
- スコープの仕組みのお陰で関数内では変数の重複をあまり気にしなくても良い。

## グローバルスコープの例

```{python}
# グローバルスコープで変数を定義
x = 1
y = 2
z = 3

# 関数fのローカルスコープ内から変数を呼び出す
def f():
    print(x, y, z)
```

```{python}
f()
```

## ローカルスコープの例

```python
# 関数fのローカルスコープ内だけで変数を定義
def f():
    x = 1
    y = 2
    z = 3

# 変数xはグローバルスコープからは見つからない
print(x)

#> NameError: name 'x' is not defined
```

## ローカルスコープからグローバル変数に書き込む

- `global`キーワードを使うとグローバル変数に書き込める。

```{python}
x = 100

def f():
    global x
    x += 1

print(x)
f()
print(x)
```

- グローバル変数は予期せぬ間違いの原因となりやすいので、基本的には安易に使用すべきではない。

## 例外処理

- 例外が発生したとき、処理を中断させる代わりに**例外の種類に応じた何らかの処理**を行わせることができる。
- 例外が発生しそうな処理を`try`節に、例外が発生したときの処理を`except`節に書く。

```{python}
a = 10
b = 0

try:
    print(a / b)
except ZeroDivisionError:
    print("bがゼロです。")
```

- Except節には複数の例外をタプルで指定することもできる。
- Except節内でtry節内の変数を使わないように注意すること(例外発生後に定義した変数は参照できない)。

## ドキュメンテーション文字列(docstring)

- 関数宣言に続いてdocstringと呼ばれるコメントを書いて関数の説明をすることができる。
- docstringは`help()`を使って参照することができたり、エディタによっては説明をポップアップできたり、後でドキュメント出力に使えたり、何かと便利。

```{python}
def add(x, y):
    """
    2つの数を足すよ!
    """
    return x + y

help(add)
```

## docstringの書き方

- docstringの書き方にはいくつかの流儀があるが、これという決定的なものはない。
- cf. [[Python]可読性を上げるための、docstringの書き方を学ぶ（NumPyスタイル） - Qiita](https://qiita.com/simonritchie/items/49e0813508cad4876b5a)

## 変数の使い所

- データをあとで使う場合だけ変数を使うこと。
- (可読性向上などの目的がなければ)以下の様に1度きりの変数を使うべきではない。

```{python}
x = 100
print(x)
```

- 上記の例であれば、直接値を渡すこと。

```{python}
print(100)
```

## チャレンジ解答

- https://github.com/nozma/the_self_taught_programmer_challenges/tree/master/ch04